
# Site settings
title: CyVerse@UNCW
email: labstapleton@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The primary source for introductory information for CyVerse@UNCW.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://CyVerse-Validate.github.io/" # the base hostname & protocol for your site
github_username: CyVerse-Validate

# Build settings
markdown: kramdown
